# Generated by Django 4.2 on 2025-06-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='plate_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
